#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == darwin* ]]; then
  export EDITOR="subl -w"
  export VISUAL="subl -w"
  export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
  export JAVA_HOME=/Library/Java/Home
  export PATH="/usr/local/share/npm/bin:/usr/local/heroku/bin:$PATH"
  
  alias gdm="git diff HEAD | subl --stay"
fi

if [[ -s "/usr/local/bin/aws_zsh_completer.sh" ]]; then
  source "/usr/local/bin/aws_zsh_completer.sh"
fi

unsetopt SHARE_HISTORY

alias gs="git status"
alias gpo='git push origin "$(git-branch-current)"'
alias gcam="git commit -a -m"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gpr="git pull --rebase"
alias gaa="git add -A"

alias bu="bundle update"
alias bi="bundle install"
alias bc="bundle console"
alias be="bundle exec"

alias rs="rors"
alias rc="rorc"

alias fetch="rsync --archive --compress --partial --progress --append --ipv4"

fpath=(~/.rvm/scripts/zsh/Completion $fpath)

et() {
  if test -n "$(find . -maxdepth 1 -name '*.sublime-project' -print -quit)"; then
    subl -s *.sublime-project
  else
    subl -s .
  fi
}
