#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == darwin* ]]; then
  export EDITOR="subl -w"
  export VISUAL="subl -w"
  export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
  export JAVA_HOME=/Library/Java/Home
  export PATH="/usr/local/share/npm/bin:/usr/local/heroku/bin:$PATH"
  
  alias gdm="git diff HEAD | subl --stay"
fi

unsetopt SHARE_HISTORY

alias gs="git status"
alias gpo='git push origin "$(git-branch-current)"'
alias gcam="git commit -a -m"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gpr="git pull --rebase"
alias gaa="git add -A"

alias bu="bundle update"
alias bi="bundle install"
alias bc="bundle console"
alias be="bundle exec"

alias rs="rors"
alias rc="rorc"

alias fetch="rsync --archive --compress --partial --progress --append --ipv4"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fpath=(~/.rvm/scripts/zsh/Completion $fpath)

et() {
  if test -n "$(find . -maxdepth 1 -name '*.sublime-project' -print -quit)"; then
    subl -s *.sublime-project
  else
    subl -s .
  fi
}

admin() {
  heroku $* --app everlane-admin
}
 
staging() {
  heroku $* --app everlane-staging
}
 
prod() {
  heroku $* --app everlane
}
 
clear_cache() {
  prod run rake cache:clear
  say "Cache cleared"
}
 
deploy_prod() {
  if deploy_admin && git push production master:master -f ;then
    say "Production deployed"
    return 0
  else
    say "Error deploying production"
    return 1
  fi
}
 
deploy_admin () {
  if git push admin master:master -f && admin run rake db:migrate && admin restart ;then
    say "Admin deployed"
    return 0
  else
    say "Error deploying admin"
    return 1
  fi
}
