#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == darwin* ]]; then
  export EDITOR="subl -w"
  export VISUAL="subl -w"
  export ANDROID_SDK_ROOT="/usr/local/Cellar/android-sdk/r20.0.1"
  export NODE_PATH="/usr/local/lib/node_modules"
  export PATH=/usr/local/share/npm/bin:$PATH
  
  alias gdm="git diff HEAD | subl --stay"
  alias et="subl ."
fi

unsetopt SHARE_HISTORY

alias gs="git status"
alias gpo='git push origin "$(git-branch-current)"'
alias gcam="git commit -a -m"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gpr="git pull --rebase"
alias gaa="git add -A"

alias bu="bundle update"
alias bi="bundle install"
alias bc="bundle console"
alias be="bundle exec"

alias rs="rors"
alias rc="rorc"

alias fetch="rsync --archive --compress --partial --progress --append --ipv4"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fpath=(~/.rvm/scripts/zsh/Completion $fpath)
